### ISSUE TITLE
Display image

### ISSUE THREAD

**Issue by x931890193** [x931890193/st7789v#1]
https://github.com/x931890193/st7789v/blob/f59ce0d2f3b5fadb1ff972584b0ca6eb35ea9b45/src/lib.rs#L859

@Gussy hey！ Maybe You can try this

**Comment by Gussy** [comment]
@x931890193 Thanks for the ping!

I have just switched to using [almindor/st7789](https://github.com/almindor/st7789) so I could use `embedded-graphics` `0.7.x`. You can check out my demo repo here: [gussy/rock5b-display](https://github.com/Gussy/rock5b-display). I tried using [almindor/mipidsi](https://github.com/almindor/mipidsi) but couldn't get it to work on linux.

Your [x931890193/waveshare-lcd](https://github.com/x931890193/waveshare-lcd) repo is interesting, is this a port of the waveshare C code? Looks like were working on similar things at the same time.

**Comment by x931890193** [comment]
> @x931890193 Thanks for the ping!
> 
> I have just switched to using [almindor/st7789](https://github.com/almindor/st7789) so I could use `embedded-graphics` `0.7.x`. You can check out my demo repo here: [gussy/rock5b-display](https://github.com/Gussy/rock5b-display). I tried using [almindor/mipidsi](https://github.com/almindor/mipidsi) but couldn't get it to work on linux.
> 
> Your [x931890193/waveshare-lcd](https://github.com/x931890193/waveshare-lcd) repo is interesting, is this a port of the waveshare C code? Looks like were working on similar things at the same time.

[x931890193/waveshare-lcd](https://github.com/x931890193/waveshare-lcd) not work 💔 ， I try to translate C code to rust，but I`m a newbee in Rust and C. Maybe you can do that.
